name: Python App Test with GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies
      run: make install
    - name: Run tests
      run: make test
    - name: Code quality checks
      run: make quality